/* Documentação da migração do banco original. Execute uma vez em banco original.
   O comando Flask preparar-banco verifica os campos e pode ser repetido. */
ALTER TABLE USUARIO ALTER SENHA TYPE VARCHAR(100);
ALTER TABLE USUARIO ADD PERFIL VARCHAR(10) DEFAULT 'leitor' NOT NULL;
ALTER TABLE USUARIO ADD BLOQUEADO SMALLINT DEFAULT 0 NOT NULL;
ALTER TABLE USUARIO ADD TENTATIVAS INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE USUARIO ADD BLOQUEADO_ATE BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE USUARIO ADD VERSAO_SESSAO INTEGER DEFAULT 0 NOT NULL;
COMMIT;
CREATE UNIQUE INDEX UX_USUARIO_EMAIL ON USUARIO (EMAIL);
COMMIT;
