CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL,
 role VARCHAR(10) NOT NULL CHECK (role IN ('admin','user')),
 blocked INTEGER NOT NULL DEFAULT 0 CHECK (blocked IN (0,1)),
 failed_attempts INTEGER NOT NULL DEFAULT 0,
 locked_until BIGINT NOT NULL DEFAULT 0,
 session_version INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS books (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title VARCHAR(200) NOT NULL UNIQUE,
 author VARCHAR(150) NOT NULL,
 publication_year INTEGER NOT NULL CHECK (publication_year BETWEEN 1 AND 9999)
);
